---

plugins:
  - jest
  - testing-library
  - jest-dom

env:
  node: true
  es2020: true

extends:
  - 'airbnb-base'
  - 'plugin:testing-library/react'
  - 'plugin:jest/recommended'
  - 'plugin:jest-dom/recommended'

parserOptions:
  ecmaVersion: 11
  sourceType: module
  ecmaFeatures:
    jsx: true

rules:
  no-console: 0
  import/extensions: 0
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]